version: '2'

services:
  postgres:
    image: dmfenton/postgis-koop
    ports:
      - "5433:5432"

  koop:
    build:
      context: ./
    links:
      - postgres
    command: node server
    ports:
      - "80:80"
    environment:
      KOOP_DB_CONN: "postgres://postgres@postgres/koop"
      KOOP_SERVER_PORT: 80
      KOOP_BUCKET_NAME:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    volumes:
     - data:/var/koop/files

volumes:
  data: {}
