postgis:
  image: kpettijohn/postgis
  ports:
    - "5432:5432"

es:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

koop:
  image: dmfenton/koop-docker-example
  links:
    - postgis
    - es
  ports:
    - "8000:8000"

koopES:
  image: dmfenton/koop-docker-example 
  links:
    - es
  environment:
    - KOOP_CACHE=es
    - fda_key=jehHtxlGgYw6afLkks8RxB2JvcRVn335aFwguU7X
  ports:
    - "8001:8000"

koopPG:
  image: dmfenton/koop-docker-example 
  command: koop postgis
  links:
    - postgis
  environment:
    - KOOP_CACHE=postgis
    - fda_key=jehHtxlGgYw6afLkks8RxB2JvcRVn335aFwguU7X
  ports:
    - "8002:8000"
