apiVersion: v1
kind: ReplicationController
metadata:
  name: koop
spec:
  replicas: 2
  selector:
    app: koop
  template:
    metadata:
      labels:
        app: koop
    spec:
      containers:
      - name: koop
        image: dmfenton/koop-docker:latest
        env:
        - name: KOOP_DB_CONN
          value: "postgres://postgres@postgres/koop"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /status
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
